In [1]:
import pandas as pd
import numpy as np
import os
from os import listdir

import scipy.stats as ss
import math

In [2]:
## Export

z_4 = 'C:/Users/admin/Desktop/_Media big data/____________10.07/Archive/exporter2/TU_VC_CHNNL_IDX_IM/year=2020/month=09/day=01/HYU_TU_VC_CHNNL_IDX_IM_20200901195710.csv'
z_4 = pd.read_csv(z_4, header=0, sep=",")

In [3]:
# #공식##########################
# CHNNL_IM_R_3M_100
# CHNNL_IM_R_3M_100
# CHNNL_IM_R_6M_100
# CHNNL_IM_F_3M_100
# CHNNL_IM_R_1W_100

# videoCount_3M / (videoCount_6M - videoCount_3M) * 0.29 + (viewCount_3M / (viewCount_6M - viewCount_3M) + likeCount_3M / (likeCount_6M - likeCount_3M)+commentCount_3M / (commentCount_6M - commentCount_3M)) / 3 * 0.71
# videoCount_6M / (videoCount_12M - videoCount_6M) * 0.29 + (viewCount_6M / (viewCount_12M - viewCount_6M) + likeCount_6M / (likeCount_12M - likeCount_6M)+commentCount_6M / (commentCount_12M - commentCount_6M)) / 3 * 0.71
# (videoCount_f6M - videoCount_f3M) / videoCount_f6M * 0.29 + ((viewCount_f6M - viewCount_f3M) / viewCount_f6M + likeCount_f6M - (likeCount_f3M) / likeCount_f6M + (commentCount_f6M - commentCount_f3M) / commentCount_f6M) / 3 * 0.71
# (videoCount_f12M - videoCount_f6M) / videoCount_f12M * 0.29 + ((viewCount_f12M - viewCount_f6M) / viewCount_f12M + likeCount_f12M - (likeCount_f6M) / likeCount_f12M + (commentCount_f12M - commentCount_f6M) / commentCount_f12M) / 3 * 0.71
# videoCount_1W/(videoCount/7)*0.29+(viewCount_1W/(viewCount_y/7)+likeCount_1W/(likeCount/7)+commentCount_1W/(commentCount/7))*0.71

In [4]:
z_4.tail(2)

,CHNNL_ID,CHNNL_NM,COL_DE,CHNNL_DC,CHNNL_CREAT_DE,CHNNL_IM_R_3M_100,CHNNL_IM_R_6M_100,CHNNL_IM_F_3M_100,CHNNL_IM_F_6M_100,CHNNL_IM_R_1W_100,CHNNL_IM_R_3M_ZSC,CHNNL_IM_R_6M_ZSC,CHNNL_IM_F_3M_ZSC,CHNNL_IM_F_6M_ZSC,CHNNL_IM_R_1W_ZSC
332,UCNuMm8d1_mahSC1TvdES0uw,국제원산지정보원,2020-09-01,NaN,2016-04-14,0.0,0.0,0.0,0.0,0.0,-14.098,-5.934,0.026,-0.062,13.772
333,UC1wjdW8A3HSQMoQeu79-yLw,한국항공우주연구원 KARI TV,2020-09-01,KARI 한국항공우주연구원은 대한민국 항공우주 분야 중심 연구기관으로서 항공우주기술...,2011-11-25,0.0,0.0,0.0,0.0,0.0,-0.181,-19.959,-0.501,8.727,104.485

In [5]:
## API

x = 'C:/Users/admin/Desktop/_Media big data/____________10.07/Archive/api/video/year=2020/month=09/day=01/hour=17/'
filepaths = [x + f for f in listdir(x) if f.endswith('.csv')]
# comment = pd.read_csv(filepaths[3], header=0, sep="|")
# comment
rawchan=[]
# for filename in filepaths:
#     temp = pd.read_csv(filename, header=0, sep="|")
#     rawchan.append(temp)

for idx, filename in enumerate(filepaths):
    try:
        temp = pd.read_csv(filename, header=0, sep="|")
        rawchan.append(temp)
    except:
        print(idx, filename)
api1=pd.concat(rawchan, axis=0, ignore_index=True)

26 C:/Users/admin/Desktop/_Media big data/____________10.07/Archive/api/video/year=2020/month=09/day=01/hour=17/server_2_UC3XKtz0LvxRsP-iFcDx8cMg.csv
61 C:/Users/admin/Desktop/_Media big data/____________10.07/Archive/api/video/year=2020/month=09/day=01/hour=17/server_2_UCAU70B23_C9jUagR6Y962TQ.csv
107 C:/Users/admin/Desktop/_Media big data/____________10.07/Archive/api/video/year=2020/month=09/day=01/hour=17/server_2_UCf0xpJR5FavkS0e6g4gd2Sg.csv

In [6]:
api1.tail(2)

,id,collectedTime,publishedAt,channelId,title,description,thumbnailUrl,tags,category,defaultLanguage,duration,caption,viewCount,likeCount,dislikeCount,commentCount
113771,lblrZipVo94,2020-09-02T01:36:42,2019-04-16T08:35:41Z,UC_LlRgzCkUxA8690k_tfoVA,2019 부산 북구청 통화연결음 '감동진 이음' : 남자어린이,"부산 북구청 새 통화연결음, 들어보셨나요?"" 송신음 대신 귀에 감기는 귀여운 목소리...",https://i.ytimg.com/vi/lblrZipVo94/default.jpg,부산북구부산북구청북구청북구청전화북구청통화북구영상북구링투유북구청음원,22,NaN,PT12S,False,104,8.0,0.0,0.0
113772,AJ6s4BQiMpc,2020-09-02T01:36:42,2019-04-16T08:35:37Z,UC_LlRgzCkUxA8690k_tfoVA,2019 부산 북구청 통화연결음 '감동진 이음' : 여자어린이,"부산 북구청 새 통화연결음, 들어보셨나요?"" 송신음 대신 귀에 감기는 귀여운 목소리...",https://i.ytimg.com/vi/AJ6s4BQiMpc/default.jpg,부산북구부산북구청북구영상북구청영상북구동영상,22,NaN,PT13S,False,109,7.0,0.0,0.0

In [7]:
## API

x1 = 'C:/Users/admin/Desktop/_Media big data/____________10.07/Archive/api/channel/year=2020/month=09/day=01/hour=17/'
filepaths = [x1 + f for f in listdir(x1) if f.endswith('.csv')]
# comment = pd.read_csv(filepaths[3], header=0, sep="|")
# comment
rawchan1=[]
# for filename in filepaths:
#     temp = pd.read_csv(filename, header=0, sep="|")
#     rawchan.append(temp)

for idx, filename in enumerate(filepaths):
    try:
        temp = pd.read_csv(filename, header=0, sep="|")
        rawchan1.append(temp)
    except:
        print(idx, filename)
api2=pd.concat(rawchan1, axis=0, ignore_index=True)

In [8]:
api2.tail(2)

,id,title,collectedTime,category,sub_category,description,publishedAt,thumbnailUrl,uploads,country,viewCount,commentCount,subscriberCount,hiddenSubscriberCount,videoCount,keywords,unsubscribedTrailer
332,UCx5nAxxlY0RBhfx59sIiCdQ,문화관광과단양군청,2020-09-01T17:40:44,P,PCB,NaN,2017-01-18T00:28:15Z,https://yt3.ggpht.com/a/AATXAJxvoXjhQ0f6DXGo7A...,UUx5nAxxlY0RBhfx59sIiCdQ,NaN,479,0,6,False,5,NaN,NaN
333,UCbA1MXOXxyUfIftVsKybvyQ,송파여성인력개발센터,2020-09-01T17:40:44,P,PSL,"서울시 지정 교육기관, 송파여성인력개발센터의 공식 유투브 채널입니다.",2015-07-08T06:45:06Z,https://yt3.ggpht.com/a/AATXAJz4Wp8QXXzzb3RPZ0...,UUbA1MXOXxyUfIftVsKybvyQ,KR,3084,0,22,False,8,송파여성인력개발센터,NaN

In [9]:
z_4.columns

Index(['CHNNL_ID', 'CHNNL_NM', 'COL_DE', 'CHNNL_DC', 'CHNNL_CREAT_DE',
       'CHNNL_IM_R_3M_100', 'CHNNL_IM_R_6M_100', 'CHNNL_IM_F_3M_100',
       'CHNNL_IM_F_6M_100', 'CHNNL_IM_R_1W_100', 'CHNNL_IM_R_3M_ZSC',
       'CHNNL_IM_R_6M_ZSC', 'CHNNL_IM_F_3M_ZSC', 'CHNNL_IM_F_6M_ZSC',
       'CHNNL_IM_R_1W_ZSC'],
      dtype='object')

In [10]:
api1.columns

Index(['id', 'collectedTime', 'publishedAt', 'channelId', 'title',
       'description', 'thumbnailUrl', 'tags', 'category', 'defaultLanguage',
       'duration', 'caption', 'viewCount', 'likeCount', 'dislikeCount',
       'commentCount'],
      dtype='object')

In [11]:
api2.columns

Index(['id', 'title', 'collectedTime', 'category', 'sub_category',
       'description', 'publishedAt', 'thumbnailUrl', 'uploads', 'country',
       'viewCount', 'commentCount', 'subscriberCount', 'hiddenSubscriberCount',
       'videoCount', 'keywords', 'unsubscribedTrailer'],
      dtype='object')

In [12]:
api1 = api1.drop(['id', 'collectedTime', 'publishedAt', 'title', 'description', 'thumbnailUrl', 
                  'tags', 'category', 'defaultLanguage', 'duration', 'caption'], axis='columns')
api2 = api2.drop(['title', 'collectedTime', 'category', 'sub_category',
       'description', 'publishedAt', 'thumbnailUrl', 'uploads', 'country',
       'hiddenSubscriberCount', 'keywords', 'unsubscribedTrailer'], axis='columns')

z_4 = z_4.drop(['CHNNL_NM', 'COL_DE', 'CHNNL_DC', 'CHNNL_CREAT_DE'], axis='columns')

In [13]:
print(len(api1.columns))
print(len(api2.columns))
print(len(z_4.columns))

5
5
11

In [14]:
api1.columns

Index(['channelId', 'viewCount', 'likeCount', 'dislikeCount', 'commentCount'], dtype='object')

In [15]:
api2.columns

Index(['id', 'viewCount', 'commentCount', 'subscriberCount', 'videoCount'], dtype='object')

In [16]:
z_4.columns

Index(['CHNNL_ID', 'CHNNL_IM_R_3M_100', 'CHNNL_IM_R_6M_100',
       'CHNNL_IM_F_3M_100', 'CHNNL_IM_F_6M_100', 'CHNNL_IM_R_1W_100',
       'CHNNL_IM_R_3M_ZSC', 'CHNNL_IM_R_6M_ZSC', 'CHNNL_IM_F_3M_ZSC',
       'CHNNL_IM_F_6M_ZSC', 'CHNNL_IM_R_1W_ZSC'],
      dtype='object')

In [17]:
api1 = api1.fillna(0)

In [18]:
orig1_df = api1.sort_values(by='channelId').reset_index(drop=True)
orig2_df = api2.sort_values(by='id').reset_index(drop=True)
z_4 = z_4.sort_values(by='CHNNL_ID').reset_index(drop=True)

In [19]:
api1 = api1.groupby('channelId').sum().reset_index()

In [20]:
api1

,channelId,viewCount,likeCount,dislikeCount,commentCount
0,UC-8R1d-KQrZy_7-EvE_w9Nw,144273,332.0,17.0,34.0
1,UC-AuHoBXFe2e6YQ3fcA2zFA,81709,599.0,10.0,27.0
2,UC-IzDX3TIwWTgOgDpXP_g_A,21511,654.0,565.0,269.0
3,UC-SRrNN7Q9bSgDAlBdjakxw,1969,6.0,1.0,0.0
4,UC-_Lr5aJ92zDKCJXAQi656A,79263,1708.0,28.0,167.0
...,...,...,...,...,...
325,UCytCg2eiaIVA-XszjDCSn-A,50102,144.0,12.0,5.0
326,UCz1W1_XpIY8bO2pGTcZ66Wg,14745658,49307.0,5694.0,11504.0
327,UCz22EWP6u08x3b3aYSMh5BQ,92144,995.0,23.0,230.0
328,UCz7YRlrTo4rFHIv0LT4vHzA,53298,1304.0,15.0,258.0
329,UCzmGNr7bHavW8SUg1n4KIMQ,5925,67.0,8.0,0.0

In [21]:
api2

,id,viewCount,commentCount,subscriberCount,videoCount
0,UCiGeWRkwZJL1ZH_1ImaZwmg,3173299,0,10300,4175
1,UCZ1Nw3mlYRJPp1XqVLD0gTw,413386,0,3010,6512
2,UC-cD-yujwHszqVkznb38jtw,212179,0,2200,883
3,UCkRgpCI9xcjIiZ4q1i9VuVA,1550386,0,2180,629
4,UCZFTAP8J_0xEjjhreKMHa4A,865294,0,3950,3119
...,...,...,...,...,...
329,UCkZMHNBwuBP7_Khmo2TV7Ug,4936,0,1120,11
330,UCmXIN48XgSKcrcKGQmWwH_Q,905,0,11,3
331,UCglumyJyxaJmoE23-J3eF2Q,110,0,6,3
332,UCx5nAxxlY0RBhfx59sIiCdQ,479,0,6,5
333,UCbA1MXOXxyUfIftVsKybvyQ,3084,0,22,8

In [22]:
z_4

,CHNNL_ID,CHNNL_IM_R_3M_100,CHNNL_IM_R_6M_100,CHNNL_IM_F_3M_100,CHNNL_IM_F_6M_100,CHNNL_IM_R_1W_100,CHNNL_IM_R_3M_ZSC,CHNNL_IM_R_6M_ZSC,CHNNL_IM_F_3M_ZSC,CHNNL_IM_F_6M_ZSC,CHNNL_IM_R_1W_ZSC
0,UC-8R1d-KQrZy_7-EvE_w9Nw,0.0,0.0,0.0,0.0,0.0,-1.531,-11.858,0.026,-0.062,4.278
1,UC-AuHoBXFe2e6YQ3fcA2zFA,0.0,0.0,0.0,0.0,0.0,-7.630,-4.430,0.026,-0.062,13.041
2,UC-IzDX3TIwWTgOgDpXP_g_A,0.0,0.0,0.0,0.0,0.0,-22.777,-0.698,0.106,0.012,14.598
3,UC-SRrNN7Q9bSgDAlBdjakxw,0.0,0.0,0.0,0.0,0.0,-22.777,-3.742,-0.208,0.013,13.820
4,UC-_Lr5aJ92zDKCJXAQi656A,0.0,0.0,0.0,0.0,0.0,-16.549,23.267,0.120,-0.398,13.378
...,...,...,...,...,...,...,...,...,...,...,...
329,UCytCg2eiaIVA-XszjDCSn-A,0.0,0.0,0.0,0.0,0.0,-13.478,-10.321,0.026,-0.062,13.908
330,UCz1W1_XpIY8bO2pGTcZ66Wg,0.0,0.0,0.0,0.0,0.0,0.689,0.901,0.828,-2.324,-5.065
331,UCz22EWP6u08x3b3aYSMh5BQ,0.0,0.0,0.0,0.0,0.0,0.000,6.096,0.026,-0.062,15.877
332,UCz7YRlrTo4rFHIv0LT4vHzA,0.0,0.0,0.0,0.0,0.0,19.046,2.946,-0.077,-3.058,7.952
333,UCzmGNr7bHavW8SUg1n4KIMQ,0.0,0.0,0.0,0.0,0.0,12.706,-2.352,0.062,-0.038,13.863

In [23]:
z_4 = z_4[z_4['CHNNL_ID'].isin(api1['channelId'])]
z_4

,CHNNL_ID,CHNNL_IM_R_3M_100,CHNNL_IM_R_6M_100,CHNNL_IM_F_3M_100,CHNNL_IM_F_6M_100,CHNNL_IM_R_1W_100,CHNNL_IM_R_3M_ZSC,CHNNL_IM_R_6M_ZSC,CHNNL_IM_F_3M_ZSC,CHNNL_IM_F_6M_ZSC,CHNNL_IM_R_1W_ZSC
0,UC-8R1d-KQrZy_7-EvE_w9Nw,0.0,0.0,0.0,0.0,0.0,-1.531,-11.858,0.026,-0.062,4.278
1,UC-AuHoBXFe2e6YQ3fcA2zFA,0.0,0.0,0.0,0.0,0.0,-7.630,-4.430,0.026,-0.062,13.041
2,UC-IzDX3TIwWTgOgDpXP_g_A,0.0,0.0,0.0,0.0,0.0,-22.777,-0.698,0.106,0.012,14.598
3,UC-SRrNN7Q9bSgDAlBdjakxw,0.0,0.0,0.0,0.0,0.0,-22.777,-3.742,-0.208,0.013,13.820
4,UC-_Lr5aJ92zDKCJXAQi656A,0.0,0.0,0.0,0.0,0.0,-16.549,23.267,0.120,-0.398,13.378
...,...,...,...,...,...,...,...,...,...,...,...
329,UCytCg2eiaIVA-XszjDCSn-A,0.0,0.0,0.0,0.0,0.0,-13.478,-10.321,0.026,-0.062,13.908
330,UCz1W1_XpIY8bO2pGTcZ66Wg,0.0,0.0,0.0,0.0,0.0,0.689,0.901,0.828,-2.324,-5.065
331,UCz22EWP6u08x3b3aYSMh5BQ,0.0,0.0,0.0,0.0,0.0,0.000,6.096,0.026,-0.062,15.877
332,UCz7YRlrTo4rFHIv0LT4vHzA,0.0,0.0,0.0,0.0,0.0,19.046,2.946,-0.077,-3.058,7.952
333,UCzmGNr7bHavW8SUg1n4KIMQ,0.0,0.0,0.0,0.0,0.0,12.706,-2.352,0.062,-0.038,13.863

In [24]:
api1 = api1[api1['channelId'].isin(z_4['CHNNL_ID'])]
api1

,channelId,viewCount,likeCount,dislikeCount,commentCount
0,UC-8R1d-KQrZy_7-EvE_w9Nw,144273,332.0,17.0,34.0
1,UC-AuHoBXFe2e6YQ3fcA2zFA,81709,599.0,10.0,27.0
2,UC-IzDX3TIwWTgOgDpXP_g_A,21511,654.0,565.0,269.0
3,UC-SRrNN7Q9bSgDAlBdjakxw,1969,6.0,1.0,0.0
4,UC-_Lr5aJ92zDKCJXAQi656A,79263,1708.0,28.0,167.0
...,...,...,...,...,...
325,UCytCg2eiaIVA-XszjDCSn-A,50102,144.0,12.0,5.0
326,UCz1W1_XpIY8bO2pGTcZ66Wg,14745658,49307.0,5694.0,11504.0
327,UCz22EWP6u08x3b3aYSMh5BQ,92144,995.0,23.0,230.0
328,UCz7YRlrTo4rFHIv0LT4vHzA,53298,1304.0,15.0,258.0
329,UCzmGNr7bHavW8SUg1n4KIMQ,5925,67.0,8.0,0.0

In [25]:
z_4 = z_4.sort_values(by='CHNNL_ID').reset_index(drop=True)
api1 = api1.sort_values(by='channelId').reset_index(drop=True)
api2 = api2.sort_values(by='id').reset_index(drop=True)

In [26]:
api2 = api2.drop(['viewCount', 'commentCount', 'subscriberCount'], axis='columns')
api2.columns = ['channelId', 'videoCount']
api2

                    channelId  videoCount
0    UC-8R1d-KQrZy_7-EvE_w9Nw          96
1    UC-AuHoBXFe2e6YQ3fcA2zFA         201
2    UC-IzDX3TIwWTgOgDpXP_g_A          21
3    UC-SRrNN7Q9bSgDAlBdjakxw          17
4    UC-_Lr5aJ92zDKCJXAQi656A         618
..                        ...         ...
329  UCytCg2eiaIVA-XszjDCSn-A           6
330  UCz1W1_XpIY8bO2pGTcZ66Wg         682
331  UCz22EWP6u08x3b3aYSMh5BQ         153
332  UCz7YRlrTo4rFHIv0LT4vHzA          95
333  UCzmGNr7bHavW8SUg1n4KIMQ          15

[334 rows x 2 columns]

In [27]:
api_t = pd.merge(left = api1 , right = api2, how = "inner", on = "channelId")
api_t

,channelId,viewCount,likeCount,dislikeCount,commentCount,videoCount
0,UC-8R1d-KQrZy_7-EvE_w9Nw,144273,332.0,17.0,34.0,96
1,UC-AuHoBXFe2e6YQ3fcA2zFA,81709,599.0,10.0,27.0,201
2,UC-IzDX3TIwWTgOgDpXP_g_A,21511,654.0,565.0,269.0,21
3,UC-SRrNN7Q9bSgDAlBdjakxw,1969,6.0,1.0,0.0,17
4,UC-_Lr5aJ92zDKCJXAQi656A,79263,1708.0,28.0,167.0,618
...,...,...,...,...,...,...
325,UCytCg2eiaIVA-XszjDCSn-A,50102,144.0,12.0,5.0,6
326,UCz1W1_XpIY8bO2pGTcZ66Wg,14745658,49307.0,5694.0,11504.0,682
327,UCz22EWP6u08x3b3aYSMh5BQ,92144,995.0,23.0,230.0,153
328,UCz7YRlrTo4rFHIv0LT4vHzA,53298,1304.0,15.0,258.0,95
329,UCzmGNr7bHavW8SUg1n4KIMQ,5925,67.0,8.0,0.0,15

In [28]:
api_t = api_t.fillna(0)

In [31]:
orig_df = api_t.copy()

In [30]:
# #공식##########################
# CHNNL_IM_R_3M_100
# CHNNL_IM_R_3M_100
# CHNNL_IM_R_6M_100
# CHNNL_IM_F_3M_100
# CHNNL_IM_R_1W_100

# videoCount_3M / (videoCount_6M - videoCount_3M) * 0.29 + (viewCount_3M / (viewCount_6M - viewCount_3M) + likeCount_3M / (likeCount_6M - likeCount_3M)+commentCount_3M / (commentCount_6M - commentCount_3M)) / 3 * 0.71
# videoCount_6M / (videoCount_12M - videoCount_6M) * 0.29 + (viewCount_6M / (viewCount_12M - viewCount_6M) + likeCount_6M / (likeCount_12M - likeCount_6M)+commentCount_6M / (commentCount_12M - commentCount_6M)) / 3 * 0.71
# (videoCount_f6M - videoCount_f3M) / videoCount_f6M * 0.29 + ((viewCount_f6M - viewCount_f3M) / viewCount_f6M + likeCount_f6M - (likeCount_f3M) / likeCount_f6M + (commentCount_f6M - commentCount_f3M) / commentCount_f6M) / 3 * 0.71
# (videoCount_f12M - videoCount_f6M) / videoCount_f12M * 0.29 + ((viewCount_f12M - viewCount_f6M) / viewCount_f12M + likeCount_f12M - (likeCount_f6M) / likeCount_f12M + (commentCount_f12M - commentCount_f6M) / commentCount_f12M) / 3 * 0.71
# videoCount_1W/(videoCount/7)*0.29+(viewCount_1W/(viewCount_y/7)+likeCount_1W/(likeCount/7)+commentCount_1W/(commentCount/7))*0.71

In [33]:
orig_df['videoCount_3M'] = orig_df['videoCount']
orig_df['videoCount_6M'] = orig_df['videoCount']
orig_df['viewCount_3M'] = orig_df['viewCount']
orig_df['viewCount_6M'] = orig_df['viewCount']
orig_df['likeCount_3M'] = orig_df['likeCount']
orig_df['likeCount_6M'] = orig_df['likeCount']
orig_df['commentCount_3M'] = orig_df['commentCount']
orig_df['commentCount_6M'] = orig_df['commentCount']

o_CHNNL_IM_R_3M_100 = orig_df['videoCount_3M']/(orig_df['videoCount_6M']-orig_df['videoCount_3M'])* 0.29 + (orig_df['viewCount_3M'] / (orig_df['viewCount_6M'] - orig_df['viewCount_3M']) + orig_df['likeCount_3M'] / (orig_df['likeCount_6M'] - orig_df['likeCount_3M'])+orig_df['commentCount_3M'] / (orig_df['commentCount_6M'] - orig_df['commentCount_3M'])) / 3 * 0.71

In [34]:
o_CHNNL_IM_R_3M_100

0      inf
1      inf
2      inf
3      NaN
4      inf
      ...
325    inf
326    inf
327    inf
328    inf
329    NaN
Length: 330, dtype: float64